### ISSUE TITLE
Dont understand this Repo

### ISSUE THREAD

**Issue by datomo** [cptunderground/cvae-papyri#1]
I have a problem with this project, I seem to not be able to set it up properly. 
Any advice.

**Comment by datomo** [comment]
Thanks for the help

**Comment by cptunderground** [comment]
Dear datomo

Thank you for your issue. The repo is still in development and no release is pushed yet. If you have any other question concerning the repo do not hesitate to ask.

Best
The cvae-papyri dev-team (aka me)
